[package]
name = "framec_tests"
version = "0.1.0"
authors = ["Fernando De la Garza <fernando.delagarza@savant.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
