name: Frame Transpiler

on: push

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./framec

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
